version: 0.2
phases:
  build:
    commands:
      - echo Build phase...
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/jb-hello-world-maven-0.2.0.jar
  discard-paths: yes
